on:
  # On Every Push to main
  push:
    branches:
      - main
  # On Every PR against main  
  pull_request:
    branches:
      - main
  # Scheduled Run 
  schedule:
  - cron: '0 0 1 * *'
  
name: Check markdown links 🔗

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args: --verbose --no-progress **/*.md **/*.html
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./KrakinzLab/out.md
          labels: report, automated issue
